### ISSUE TITLE
I am enthusiastic about the opportunity to join your team and apply my years of expertise to contribute to your projects' success.

### ISSUE THREAD

**Issue by kentaurse** [circles-project/circles-ios#10]
Hi, I'm Ethan Tan, a seasoned web full-stack and blockchain developer with over 8 years of experience in the industry. I specialize in building robust, scalable web applications and innovative blockchain solutions. Leveraging my expertise in frameworks like React.js, Vue.js, and Next.js, along with my proficiency in Solidity for smart contract development, I deliver high-quality, secure, and efficient solutions tailored to meet your specific needs.

**Comment by cvwright** [comment]
Take your spam somewhere else.  If you had looked at this project for two seconds you would know that those skills are unrelated to what we're doing here.
